export const countries = [
    { value: 'Algeria', label: 'Algeria' },
    { value: 'Antigua', label: 'Antigua' },
    { value: 'Australia', label: 'Australia' },
    { value: 'Austria', label: 'Austria' },
    { value: 'Azerbaijan', label: 'Azerbaijan' },
    { value: 'Bangladesh', label: 'Bangladesh' },
    { value: 'Belgium', label: 'Belgium' },
    { value: 'Bolivia', label: 'Bolivia' },
    { value: 'Bosnia-Herzegovina', label: 'Bosnia-Herzegovina' },
    { value: 'Brazil', label: 'Brazil' },
    { value: 'Bulgaria', label: 'Bulgaria' },
    { value: 'Cambodia', label: 'Cambodia' },
    { value: 'Canada', label: 'Canada' },
    { value: 'Cayman Islands', label: 'Cayman Islands' },
    { value: 'Chile', label: 'Chile' },
    { value: 'China', label: 'China' },
    { value: 'Colombia', label: 'Colombia' },
    { value: 'Costa Rica', label: 'Costa Rica' },
    { value: 'Croatia', label: 'Croatia' },
    { value: 'Cyprus (Southern)', label: 'Cyprus (Southern)' },
    { value: 'Cyprus', label: 'Cyprus' },
    { value: 'Czech Republic', label: 'Czech Republic' },
    { value: 'Democratic Republic of the Congo', label: 'Democratic Republic of the Congo' },
    { value: 'Denmark', label: 'Denmark' },
    { value: 'Egypt', label: 'Egypt' },
    { value: 'Estonia', label: 'Estonia' },
    { value: 'Falkland Islands', label: 'Falkland Islands' },
    { value: 'Finland', label: 'Finland' },
    { value: 'France', label: 'France' },
    { value: 'Georgia', label: 'Georgia' },
    { value: 'Germany', label: 'Germany' },
    { value: 'Greece', label: 'Greece' },
    { value: 'Guernsey', label: 'Guernsey' },
    { value: 'Hong Kong', label: 'Hong Kong' },
    { value: 'Hungary', label: 'Hungary' },
    { value: 'Iceland', label: 'Iceland' },
    { value: 'India', label: 'India' },
    { value: 'Ireland', label: 'Ireland' },
    { value: 'Israel', label: 'Israel' },
    { value: 'Italy', label: 'Italy' },
    { value: 'Japan', label: 'Japan' },
    { value: 'Jersey', label: 'Jersey' },
    { value: 'Jordan', label: 'Jordan' },
    { value: 'Kazakhstan', label: 'Kazakhstan' },
    { value: 'Kenya', label: 'Kenya' },
    { value: 'Kingdom of Saudi Arabia', label: 'Kingdom of Saudi Arabia' },
    { value: 'Korea (North)', label: 'Korea (North)' },
    { value: 'Korea (South)', label: 'Korea (South)' },
    { value: 'Latvia', label: 'Latvia' },
    { value: 'Lebanon', label: 'Lebanon' },
    { value: 'Lithuania', label: 'Lithuania' },
    { value: 'Luxembourg', label: 'Luxembourg' },
    { value: 'Malaysia', label: 'Malaysia' },
    { value: 'Malta', label: 'Malta' },
    { value: 'Martinique', label: 'Martinique' },
    { value: 'Mauritius', label: 'Mauritius' },
    { value: 'Morocco', label: 'Morocco' },
    { value: 'Mozambique', label: 'Mozambique' },
    { value: 'Netherlands', label: 'Netherlands' },
    { value: 'New Zealand', label: 'New Zealand' },
    { value: 'Nigeria', label: 'Nigeria' },
    { value: 'Norway', label: 'Norway' },
    { value: 'Pakistan', label: 'Pakistan' },
    { value: 'Paraguay', label: 'Paraguay' },
    { value: 'Philippines', label: 'Philippines' },
    { value: 'Poland', label: 'Poland' },
    { value: 'Portugal', label: 'Portugal' },
    { value: 'Puerto Rico', label: 'Puerto Rico' },
    { value: 'Republic Of Belarus', label: 'Republic Of Belarus' },
    { value: 'Republic Of Serbia', label: 'Republic Of Serbia' },
    { value: 'Republic Of Yemen', label: 'Republic Of Yemen' },
    { value: 'Romania', label: 'Romania' },
    { value: 'Russia', label: 'Russia' },
    { value: 'Seychelles', label: 'Seychelles' },
    { value: 'Slovak Republic', label: 'Slovak Republic' },
    { value: 'Slovenia', label: 'Slovenia' },
    { value: 'South Africa', label: 'South Africa' },
    { value: 'Spain', label: 'Spain' },
    { value: 'State of Qatar', label: 'State of Qatar' },
    { value: 'Sudan', label: 'Sudan' },
    { value: 'Sweden', label: 'Sweden' },
    { value: 'Switzerland', label: 'Switzerland' },
    { value: 'Taiwan', label: 'Taiwan' },
    { value: 'Tanzania (Africa)', label: 'Tanzania (Africa)' },
    { value: 'Thailand', label: 'Thailand' },
    { value: 'Trinidad & Tobago', label: 'Trinidad & Tobago' },
    { value: 'Turkey', label: 'Turkey' },
    { value: 'U.S.A.', label: 'U.S.A.' },
    { value: 'Uganda', label: 'Uganda' },
    { value: 'Ukraine', label: 'Ukraine' },
    { value: 'United Arab Emirates', label: 'United Arab Emirates' },
    { value: 'United Kingdom', label: 'United Kingdom' },
    { value: 'Uruguay', label: 'Uruguay' },
    { value: 'Venezuela', label: 'Venezuela' },
    { value: 'Vietnam', label: 'Vietnam' },
    { value: 'West Africa', label: 'West Africa' },
    { value: 'Zimbabwe', label: 'Zimbabwe' },
];
